typography_spectrum: 0.20181860332377255
content_rating:
  adult: false
color:
  brandStrength: 0.926601127255708
  lightness: 0.4725974511820823
  saturation: 0.146646331762895
  rhythmicContrast: 0.9944761658553034
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
layout_spectrum: 0.8825863311067224
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/ccab122b-d847-4286-b5d6-f8ee9c61d96a.jpg
name: Soul Meets Body
navigation:
  - id: 'http://www.soulmeetsbody.biz/about'
    url: 'http://www.soulmeetsbody.biz/about'
    name: About
    type: external
  - id: 'http://www.soulmeetsbody.biz/benefits'
    url: 'http://www.soulmeetsbody.biz/benefits'
    name: Benefits
    type: external
  - id: 'http://www.soulmeetsbody.biz/for-the-athlete'
    url: 'http://www.soulmeetsbody.biz/for-the-athlete'
    name: For the athlete
    type: external
  - id: 'http://www.soulmeetsbody.biz/Treatments'
    url: 'http://www.soulmeetsbody.biz/Treatments'
    name: Treatments
    type: external
  - id: >-
      https://www.google.com/maps/place/3105+W+Jameson+St,+Seattle,+WA+98199/@47.659914,-122.397898,15z/data=!4m5!3m4!1s0x549015eb44f9be8f:0x81d4ece8bc998c9d!8m2!3d47.6598718!4d-122.39798?hl=en-US
    url: >-
      https://www.google.com/maps/place/3105+W+Jameson+St,+Seattle,+WA+98199/@47.659914,-122.397898,15z/data=!4m5!3m4!1s0x549015eb44f9be8f:0x81d4ece8bc998c9d!8m2!3d47.6598718!4d-122.39798?hl=en-US
    name: Find us
    type: external
title: massage & bodywork
